server:
  port: 10000
spring:
  activemq:
    #代理地址
    broker-url: tcp://192.168.239.128:61616
    #账号
    user: system
    #密码
    password: manager
    #false 内存模式启动代理 true 远程访问代理
    in-memory: false
    #jms连接池
    pool:
      enabled: true
      max-connections: 50
    #包配置
    packages:
      #是否全部受信任
      trust-all: true
      #单独配置受信任的包
      trusted: com.activemq.demo
